# settings.py
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FPS = 60
PLAYER_SPEED = 300
BULLET_SPEED = 500
ENEMY_SPEED = 100
PLAYER_MAX_HP = 5
PLAYER_MAX_AMMO = 50
ENEMY_HP = 2
TILE_SIZE = 50
WORLD_WIDTH = 2000
WORLD_HEIGHT = 2000

# 掉落参数
ENEMY_GOLD_DROP_MIN = 0
ENEMY_GOLD_DROP_MAX = 2
ENEMY_AMMO_DROP_CHANCE = 0.5
ENEMY_HEALTH_DROP_CHANCE = 0.25
AMMO_PACK_VALUE = 10
HEALTH_PACK_VALUE = 1

# 物品消失时间（秒）
ITEM_LIFESPAN = 60.0

# 门的位置（世界坐标）
DOOR_X = 512
DOOR_Y = 200
DOOR_WIDTH = 64
DOOR_HEIGHT = 64

# 银行摊位位置（安全区内）
BANK_X = 300
BANK_Y = 300
BANK_WIDTH = 64
BANK_HEIGHT = 64

# 游戏机制参数
MIN_ENEMIES = 3                     # 战区最少敌人数
ZONE_SWITCH_COOLDOWN = 5.0          # 切换区域冷却时间（秒）